name: "Feature request"
description: "Suggest an idea or enhancement."
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve the project. Please share as much context as you can.
  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "A short, clear description of the feature."
      placeholder: "Add support for incremental training"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: "Problem to solve"
      description: "What problem does this feature address?"
      placeholder: "I'm unable to... because..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: "Proposed solution"
      description: "What would you like to see? Provide examples or API ideas."
      placeholder: "A new parameter on fit() that..."
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives considered"
      description: "Any workarounds or alternative approaches you've tried."
      placeholder: "I tried..., but..."
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Links, references, or screenshots."
    validations:
      required: false
